name: "Setup Pico Toolchain"
description: "downloads the arm gnu toolchain and the pico sdk and then sets PICO_SDK_PATH and ARM_GNU_TOOLCHAIN_PATH accordingly"
author: David Wild
branding: 
  icon: "activity"
  color: "red"

inputs:
  arm-gnu-toolchain-version:
    description: 'Version of the arm gnu toolchain'
    required: true
    default: '13.2.rel1'

runs:
  using: "composite"
  steps:
    - name: Install Arm Gnu Toolchain
      run: |
        ${{ github.action_path }}/scripts/install-arm-gnu-toolchain.sh -v ${{ inputs.arm-gnu-toolchain-version }}
        echo "ARM_GNU_TOOLCHAIN_PATH=$ARM_GNU_TOOLCHAIN_PATH" >> $GITHUB_ENV
      shell: bash

    - name: Install Pico SDK
      run: |
        ${{ github.action_path }}/scripts/install-pico-sdk.sh
        echo "PICO_SDK_PATH=$PICO_SDK_PATH" >> $GITHUB_ENV
      shell: bash
